import type { JournalPost } from "@/lib/types";

export const journalPosts: JournalPost[] = [
  {
    id: "jp-01",
    title: "Why I'm Rebuilding a 1978 Toyota Chinook",
    slug: "why-rebuild-a-1978-chinook",
    excerpt:
      "It started as a forgotten camper in a shed. Here's why a rare Toyota Chinook is worth an obsessive rebuild — and what it's going to become.",
    contentType: "Project Reflection",
    publishedAt: "2026-04-20",
    featuredImage: {
      src: "/journal/why-rebuild.jpg",
      alt: "The original 1978 Toyota Chinook as found, parked in the workshop",
      width: 1600,
      height: 900,
    },
    categories: ["Story"],
    tags: ["Chinook", "Toyota", "planning"],
    featured: true,
    readingMinutes: 6,
    body: [
      "The Toyota Chinook is one of those vehicles most people have never heard of, and the ones who have never forget it. Built on an early Hilux platform and fitted with a fibreglass camper body, it was a rare, oddball adventure vehicle decades ahead of the overlanding trend.",
      "This one is a 1978 model. When I found it, the body was tired but honest, and the running gear was well past its use-by date. The romantic option is a faithful restoration. The interesting option — the one worth filming — is something else entirely.",
      "The plan is to keep the character of the Chinook body and completely modernise everything underneath it: an 80 Series LandCruiser chassis, a 6.0-litre V8, a six-speed automatic, a custom fuel system and a fully digital electrical platform. Vintage on the outside, modern engineering underneath.",
      "This website is the permanent home for that story — the decisions, the mistakes, the fabrication and eventually the travel. The build is only the beginning.",
    ],
    buildSystemSlugs: ["80-series-chassis"],
  },
  {
    id: "jp-02",
    title: "Why I Chose an 80 Series LandCruiser Chassis",
    slug: "why-80-series-chassis",
    excerpt:
      "Coil suspension, full-floating axles and a bulletproof reputation. The case for putting a vintage camper on a modern LandCruiser platform.",
    contentType: "Engineering Explanation",
    publishedAt: "2026-06-10",
    featuredImage: {
      src: "/journal/why-80-series.jpg",
      alt: "The donor LandCruiser 80 Series body alongside the Chinook front clip",
      width: 1600,
      height: 900,
    },
    categories: ["Build"],
    tags: ["chassis", "LandCruiser", "80 series"],
    featured: true,
    readingMinutes: 8,
    body: [
      "The original Hilux-derived chassis under a 1978 Chinook is a product of its era: leaf springs, modest brakes, and running gear that was never intended to carry a V8 and a loaded camper across a continent.",
      "The 80 Series LandCruiser is the opposite. Coil suspension front and rear, full-floating axles, a boxed frame and a driveline with a legendary reputation for surviving abuse. It's the platform overlanders trust for exactly this kind of travel.",
      "Choosing it wasn't only about capability. Parts availability, a huge aftermarket and known-good geometry mean fewer unknowns during the build and easier repairs on the road.",
    ],
    buildSystemSlugs: ["80-series-chassis"],
    relatedVideoId: "v-06",
    specifications: [
      { label: "Suspension", value: "Coil front & rear" },
      { label: "Axles", value: "Full-floating" },
    ],
  },
  {
    id: "jp-03",
    title: "Extending the Wheelbase Without a Chassis Table",
    slug: "extending-the-wheelbase",
    excerpt:
      "Cutting a LandCruiser frame in a home workshop, sleeving it, and keeping everything dead straight.",
    contentType: "Workshop Story",
    publishedAt: "2026-06-30",
    featuredImage: {
      src: "/journal/extending-wheelbase.jpg",
      alt: "The Chinook up on its new stance mid-fabrication with the front clip removed",
      width: 1600,
      height: 900,
    },
    categories: ["Build"],
    tags: ["fabrication", "welding", "chassis"],
    readingMinutes: 7,
    body: [
      "Extending a chassis is one of those jobs that sounds terrifying until you break it into steps. The maths comes first: where the body needs to sit, where the axles are, and what that does to rear overhang.",
      "Without a proper chassis table, the whole game is controlling distortion. I built a simple jig, made the cut, sleeved the frame internally and welded in short staggered passes to keep heat down and the rails true.",
      "It's the kind of task where measuring obsessively beforehand saves you from an expensive mistake you can't un-weld.",
    ],
    buildSystemSlugs: ["wheelbase-extension"],
    relatedVideoId: "v-07",
  },
  {
    id: "jp-04",
    title: "Understanding Australia's 60% Rear Overhang Rule",
    slug: "60-percent-overhang-rule",
    excerpt:
      "A plain-English look at the rear overhang rule and how it shaped the Chinook's wheelbase.",
    contentType: "Technical Guide",
    publishedAt: "2026-07-02",
    featuredImage: {
      src: "/journal/overhang-rule.jpg",
      alt: "Side profile of the lifted Chinook showing body length relative to the axles",
      width: 1600,
      height: 900,
    },
    categories: ["Engineering"],
    tags: ["compliance", "engineering", "Australia"],
    readingMinutes: 5,
    body: [
      "Australian rules limit how far a vehicle body can extend behind the rear axle — broadly, rear overhang shouldn't exceed 60% of the wheelbase. For a camper with a long body, that number drives the whole chassis plan.",
      "It's why the wheelbase extension isn't arbitrary. Stretch the chassis and you move the rear axle rearward relative to the body, bringing overhang back inside the limit while improving weight distribution.",
      "This is general information based on this specific project — always confirm current requirements with a qualified engineer for your build and state.",
    ],
    buildSystemSlugs: ["wheelbase-extension"],
  },
  {
    id: "jp-05",
    title: "Choosing the L98 6.0-Litre V8",
    slug: "choosing-the-l98-v8",
    excerpt:
      "Why an alloy GM V8 makes sense for a heavy camper that has to move across a continent.",
    contentType: "Engineering Explanation",
    publishedAt: "2026-07-08",
    featuredImage: {
      src: "/journal/choosing-l98.jpg",
      alt: "The L98 V8 on a pallet in front of the Chinook camper body",
      width: 1600,
      height: 900,
    },
    categories: ["Build"],
    tags: ["engine", "V8", "LS", "powertrain"],
    featured: true,
    readingMinutes: 7,
    body: [
      "A loaded camper is heavy, and heavy vehicles need torque — not peaky power. The L98 6.0-litre is an alloy V8 that makes effortless low-down torque, stays relatively light, and has an enormous parts and tuning ecosystem behind it.",
      "Reliability and serviceability matter more than headline numbers when you're a thousand kilometres from the nearest workshop. The L-series V8 has proven itself in exactly these conversions.",
      "Paired with the 6L80E automatic, it should make the Chinook genuinely pleasant to drive loaded — relaxed on the highway, tractable in low range.",
    ],
    buildSystemSlugs: ["engine-l98-v8", "6l80e-transmission"],
    relatedVideoId: "v-08",
  },
  {
    id: "jp-06",
    title: "Designing the Chinook's Digital Dashboard",
    slug: "designing-the-digital-dashboard",
    excerpt:
      "A hybrid Raspberry Pi + microcontroller architecture that runs the whole camper — and keeps working if the screen doesn't.",
    contentType: "Video Companion Article",
    publishedAt: "2026-05-31",
    featuredImage: {
      src: "/journal/digital-dashboard.jpg",
      alt: "The Chinook's halo LED headlights lit at dusk",
      width: 1600,
      height: 900,
    },
    categories: ["Electrical", "Web"],
    tags: ["electronics", "software", "dashboard", "MQTT"],
    featured: true,
    readingMinutes: 9,
    body: [
      "This is where the two halves of the project meet: fabrication and code. The camper's control system is designed like a small distributed network rather than one big brain.",
      "A Raspberry Pi 5 runs the touchscreen dashboard, maps and media. But it never directly switches a critical load. That job belongs to rugged ESP32 and Teensy controllers wired to relays, sensors and physical fallback switches.",
      "Everything shares one central state model — a single JSON contract describing power, vehicle, habitat, lighting, audio and security. The UI reads it, the controllers publish it, and MQTT keeps them in sync. If the screen reboots, the lights, water and fridge keep working.",
      "It's the same design thinking as the vehicle itself: build reliable, modular systems where one failure doesn't take down the whole rig.",
    ],
    buildSystemSlugs: ["electrical-control-systems"],
    relatedVideoId: "v-05",
  },
  {
    id: "jp-07",
    title: "Planning a 200-Litre Fuel System",
    slug: "planning-the-fuel-system",
    excerpt: "Sizing range for desert crossings, and building a tank that survives corrugations.",
    contentType: "Build Update",
    publishedAt: "2026-07-11",
    featuredImage: {
      src: "/journal/fuel-system.jpg",
      alt: "The Chinook parked in the workshop, front bull bar and quad lights visible",
      width: 1600,
      height: 900,
    },
    categories: ["Build"],
    tags: ["fuel", "fabrication", "remote travel"],
    readingMinutes: 5,
    body: [
      "Range is freedom in remote Australia. The goal is comfortable distance between fuel stops with a safety margin, which points to a large custom tank sized around the extended chassis.",
      "EFI needs consistent fuel pickup, so surge control and baffling matter — especially on corrugated roads and steep angles where fuel sloshes away from the pickup.",
    ],
    buildSystemSlugs: ["custom-fuel-system"],
  },
];
