import type { JournalPost } from "@/lib/types";

export const journalPosts: JournalPost[] = [
  {
    id: "jp-01",
    title: "Why I'm Rebuilding a 1978 Toyota Chinook",
    slug: "why-rebuild-a-1978-chinook",
    excerpt:
      "It started as a forgotten vintage camper in a shed. Here's why a rare Toyota Chinook is worth an extreme rebuild — and what this unique build will become.",
    contentType: "Project Reflection",
    publishedAt: "2026-04-20",
    featuredImage: {
      src: "/journal/why-rebuild.jpg",
      alt: "The original 1978 Toyota Chinook vintage camper as found, parked in the workshop",
      width: 1600,
      height: 900,
    },
    categories: ["Story"],
    tags: ["Chinook", "Toyota", "planning"],
    featured: true,
    readingMinutes: 6,
    body: [
      "The Toyota Chinook is one of those vehicles most people have never heard of, and the ones who have never forget it. Built on an early Hilux platform and fitted with a fibreglass camper body, it was a rare, oddball vintage camper decades ahead of the overlanding trend.",
      "This one is a 1978 model. When I found it, the body was tired but honest, and the running gear was well past its use-by date. The romantic option is a faithful restoration. The interesting option — the one worth filming — is something extreme.",
      "The plan is to keep the character of this vintage camper body and build an extremely engineered 4x4 underneath it: an 80 Series LandCruiser chassis, a 6.0-litre V8, a six-speed automatic, a custom fuel system and a fully digital electrical platform. A unique build — vintage on the outside, serious engineering underneath.",
      "This website is the permanent home for that story — the decisions, the mistakes, the fabrication and eventually the travel. This extreme build is only the beginning.",
    ],
    buildSystemSlugs: ["80-series-chassis"],
  },
  {
    id: "jp-02",
    title: "Why I Chose an 80 Series LandCruiser Chassis",
    slug: "why-80-series-chassis",
    excerpt:
      "Coil suspension, full-floating axles and a bulletproof reputation. The case for building an extremely engineered vintage 4x4 camper on a modern LandCruiser platform.",
    contentType: "Engineering Explanation",
    publishedAt: "2026-06-10",
    featuredImage: {
      src: "/journal/why-80-series.jpg",
      alt: "The donor LandCruiser 80 Series body alongside the vintage Chinook front clip",
      width: 1600,
      height: 900,
    },
    categories: ["Build"],
    tags: ["chassis", "LandCruiser", "80 series"],
    featured: true,
    readingMinutes: 8,
    body: [
      "The original Hilux-derived chassis under a 1978 Chinook is a product of its era: leaf springs, modest brakes, and running gear that was never intended to carry a V8 and a loaded extreme camper across a continent.",
      "The 80 Series LandCruiser is the opposite. Coil suspension front and rear, full-floating axles, a boxed frame and a driveline with a legendary reputation for surviving abuse. It's the platform overlanders trust for exactly this kind of extreme travel.",
      "Choosing it wasn't only about capability. Parts availability, a huge aftermarket and known-good geometry mean fewer unknowns during this unique build and easier repairs on the road.",
    ],
    buildSystemSlugs: ["80-series-chassis"],
    relatedVideoId: "v-06",
    specifications: [
      { label: "Suspension", value: "Coil front & rear" },
      { label: "Axles", value: "Full-floating" },
    ],
  },
  {
    id: "jp-03",
    title: "Extending the Wheelbase Without a Chassis Table",
    slug: "extending-the-wheelbase",
    excerpt:
      "Cutting a LandCruiser frame in a home workshop, sleeving it, and keeping everything dead straight.",
    contentType: "Workshop Story",
    publishedAt: "2026-06-30",
    featuredImage: {
      src: "/journal/extending-wheelbase.jpg",
      alt: "The Chinook up on its new stance mid-fabrication with the front clip removed",
      width: 1600,
      height: 900,
    },
    categories: ["Build"],
    tags: ["fabrication", "welding", "chassis"],
    readingMinutes: 7,
    body: [
      "Extending a chassis is one of those jobs that sounds terrifying until you break it into steps. The maths comes first: where the body needs to sit, where the axles are, and what that does to rear overhang.",
      "Without a proper chassis table, the whole game is controlling distortion. I built a simple jig, made the cut, sleeved the frame internally and welded in short staggered passes to keep heat down and the rails true.",
      "It's the kind of task where measuring obsessively beforehand saves you from an expensive mistake you can't un-weld.",
    ],
    buildSystemSlugs: ["wheelbase-extension"],
    relatedVideoId: "v-07",
  },
  {
    id: "jp-04",
    title: "Understanding Australia's 60% Rear Overhang Rule",
    slug: "60-percent-overhang-rule",
    excerpt:
      "A plain-English look at the rear overhang rule and how it shaped the Chinook's wheelbase.",
    contentType: "Technical Guide",
    publishedAt: "2026-07-02",
    featuredImage: {
      src: "/journal/overhang-rule.jpg",
      alt: "Side profile of the lifted Chinook showing body length relative to the axles",
      width: 1600,
      height: 900,
    },
    categories: ["Engineering"],
    tags: ["compliance", "engineering", "Australia"],
    readingMinutes: 5,
    body: [
      "Australian rules limit how far a vehicle body can extend behind the rear axle — broadly, rear overhang shouldn't exceed 60% of the wheelbase. For a camper with a long body, that number drives the whole chassis plan.",
      "It's why the wheelbase extension isn't arbitrary. Stretch the chassis and you move the rear axle rearward relative to the body, bringing overhang back inside the limit while improving weight distribution.",
      "This is general information based on this specific project — always confirm current requirements with a qualified engineer for your build and state.",
    ],
    buildSystemSlugs: ["wheelbase-extension"],
  },
  {
    id: "jp-05",
    title: "Choosing the L98 6.0-Litre V8",
    slug: "choosing-the-l98-v8",
    excerpt:
      "Why an alloy GM V8 makes sense for an extreme camper that has to move across a continent.",
    contentType: "Engineering Explanation",
    publishedAt: "2026-07-08",
    featuredImage: {
      src: "/journal/choosing-l98.jpg",
      alt: "The L98 V8 on a pallet in front of the vintage Chinook camper body",
      width: 1600,
      height: 900,
    },
    categories: ["Build"],
    tags: ["engine", "V8", "LS", "powertrain"],
    featured: true,
    readingMinutes: 7,
    body: [
      "A six-litre V8 probably isn't the first choice most people would make when building an extreme camper for remote touring. But I never needed massive power — the original 18R was gutless. This unique build is about torque, driveability, and honestly, economy.",
      "A stock LS with a 6L80E behind it is surprisingly economical on the highway. As economical as a brick on wheels can be, anyway. I should be able to get decent mileage out of it.",
      "I could have gone an M57 diesel with an 8HP eight-speed automatic, but here's the thing about the LS: being a Commodore motor, they're everywhere. I can walk into any wrecking yard in Australia and find parts for that engine or gearbox. If I'm remote and something breaks, I can get spares shipped fast. I didn't want to be dealing with something that wasn't readily available.",
      "The last piece was the wiring. I can buy a standalone harness, plug it in, connect a few wires, and tune it as-is. I can leave the stock ECU and transmission computer, tune it for the tyres and gear ratios, and just drive. Engine in to wiring done should be a fast process — and that's exactly what I want for this extremely engineered vintage 4x4.",
    ],
    buildSystemSlugs: ["engine-l98-v8", "6l80e-transmission"],
    relatedVideoId: "v-08",
  },
  {
    id: "jp-06",
    title: "Designing the Chinook's Digital Dashboard",
    slug: "designing-the-digital-dashboard",
    excerpt:
      "A hybrid Raspberry Pi + microcontroller architecture that runs the whole camper — and keeps working if the screen doesn't.",
    contentType: "Video Companion Article",
    publishedAt: "2026-05-31",
    featuredImage: {
      src: "/journal/digital-dashboard.jpg",
      alt: "The Chinook's halo LED headlights lit at dusk",
      width: 1600,
      height: 900,
    },
    categories: ["Electrical", "Web"],
    tags: ["electronics", "software", "dashboard", "MQTT"],
    featured: true,
    readingMinutes: 9,
    body: [
      "This is where the two halves of the project meet: fabrication and code. The camper's control system is designed like a small distributed network rather than one big brain.",
      "A Raspberry Pi 5 runs the touchscreen dashboard, maps and media. But it never directly switches a critical load. That job belongs to rugged ESP32 and Teensy controllers wired to relays, sensors and physical fallback switches.",
      "Everything shares one central state model — a single JSON contract describing power, vehicle, habitat, lighting, audio and security. The UI reads it, the controllers publish it, and MQTT keeps them in sync. If the screen reboots, the lights, water and fridge keep working.",
      "It's the same design thinking as the vehicle itself: build reliable, modular systems where one failure doesn't take down the whole rig.",
    ],
    buildSystemSlugs: ["electrical-control-systems"],
    relatedVideoId: "v-05",
  },
  {
    id: "jp-07",
    title: "Planning a 200-Litre Fuel System",
    slug: "planning-the-fuel-system",
    excerpt: "Sizing range for desert crossings, and building a tank that survives corrugations.",
    contentType: "Build Update",
    publishedAt: "2026-07-11",
    featuredImage: {
      src: "/journal/fuel-system.jpg",
      alt: "The Chinook parked in the workshop, front bull bar and quad lights visible",
      width: 1600,
      height: 900,
    },
    categories: ["Build"],
    tags: ["fuel", "fabrication", "remote travel"],
    readingMinutes: 5,
    body: [
      "Range is freedom in remote Australia. The goal is comfortable distance between fuel stops with a safety margin, which points to a large custom tank sized around the extended chassis.",
      "EFI needs consistent fuel pickup, so surge control and baffling matter — especially on corrugated roads and steep angles where fuel sloshes away from the pickup.",
    ],
    buildSystemSlugs: ["custom-fuel-system"],
  },
  {
    id: "jp-08",
    title: "47 Years of Minimal Use",
    slug: "47-years-of-minimal-use",
    excerpt:
      "This vintage camper's original interior survived nearly five decades virtually untouched. Here's what I found when I stripped it out — and why it had to go.",
    contentType: "Workshop Story",
    publishedAt: "2026-07-16",
    featuredImage: {
      src: "/journal/interior-original-overview.png",
      alt: "The original 1978 vintage Chinook interior with pop-top raised, showing the dinette, overcab bed and vintage canvas",
      width: 1290,
      height: 2796,
    },
    gallery: [
      {
        src: "/journal/interior-original-overview.png",
        alt: "The original 1978 vintage Chinook interior with pop-top raised, showing the dinette, overcab bed and vintage canvas",
        width: 1290,
        height: 2796,
      },
      {
        src: "/journal/interior-dinette.png",
        alt: "The original vintage Chinook dinette booth with striped upholstery and woodgrain laminate table",
        width: 1290,
        height: 2796,
      },
      {
        src: "/journal/interior-cabinetry.png",
        alt: "Original woodgrain cabinetry and drawers with brass knobs inside the vintage Chinook",
        width: 1290,
        height: 2796,
      },
      {
        src: "/journal/interior-fridge.png",
        alt: "The original vintage fridge unit with woodgrain panel door",
        width: 1290,
        height: 2796,
      },
    ],
    categories: ["Build", "Story"],
    tags: ["Chinook", "interior", "restoration", "van life"],
    readingMinutes: 4,
    body: [
      "When I picked up this vintage camper, the interior was exactly as it left the factory in 1978. Forty-seven years of sitting — minimal use, maximum preservation. It was a time capsule.",
      "The canvas, however, told a different story. Black mould had taken hold in the worst spots, the kind that comes from years of sitting in sheds and garages without airflow. Cleaning it off was the first job — tedious but satisfying.",
      "Once the mould was gone, I could have kept the original interior. Technically, it was usable. But usable isn't the same as liveable. The vinyl was tired, the cabinetry was dated, and the whole thing felt like it belonged in a different era. Which, of course, it did.",
      "The goal was never a museum restoration. This unique build is about creating an extremely engineered vintage 4x4 camper — something that looks vintage on the outside but lives like a 2026 extreme camper on the inside. That meant gutting everything and starting fresh.",
      "Stripping it out was bittersweet. Tucked behind panels and under seats, I found fragments of the Chinook's past life: old receipts from WA, a faded service book with every stamp since new, handwritten notes. Forty-seven years of memories made in this little vintage camper, all heading for the bin so something new could take its place.",
      "The service records were phenomenal — a complete history from the first oil change to the last. It's rare to find paperwork like that with a vehicle this old. Whoever owned it cared, even if they didn't use it much.",
      "Now the shell sits empty. No carpet, no cabinetry, no canvas. Just bare fibreglass walls and the faint smell of old camper. It's ready for the next chapter: a proper fit-out designed for serious Australian adventure.",
    ],
  },
];
