import type { Product } from "@/lib/types";

/** Gear directory — products used on the build with clear disclosures. */
export const products: Product[] = [
  {
    id: "pr-wheels",
    name: "KMC KM552 IMS",
    slug: "kmc-km552-ims",
    brandName: "KMC Wheels",
    brandSlug: "kmc-wheels",
    category: "Automotive",
    image: {
      src: "/gear/kmc-ims.png",
      alt: "KMC KM552 IMS wheel — gloss silver with machined face",
      width: 1000,
      height: 1000,
    },
    summary:
      "A reimagined version of KMC's famous Impact race wheel — monoblock construction with a simulated beadlock ring. Run in 17×8.5 with a −10 offset on the 80 Series' 6×139.7 pattern.",
    useCase: "Rolling stock for the loaded Chinook, on-road and trail.",
    reasonSelected:
      "Monoblock strength, a proper simulated-beadlock look, and a −10 offset that fills the arches while clearing the 80 Series brakes.",
    sponsorshipStatus: "supplied",
    purchaseUrl: "https://www.kmcwheels.com/kmc-ims",
    specifications: [
      { label: "Diameter", value: "17×8.5" },
      { label: "Bolt Pattern", value: "6×139.7" },
      { label: "Offset", value: "−10", unit: "mm" },
      { label: "Finish", value: "Gloss Silver / Machined" },
      { label: "Load Rating", value: "2500", unit: "lb" },
      { label: "Weight", value: "30.4", unit: "lb" },
    ],
    buildSystemSlugs: ["80-series-chassis"],
    region: "AU",
    featured: true,
  },
  {
    id: "pr-tyres",
    name: "Fuel Gripper M/T",
    slug: "fuel-gripper-mt",
    brandName: "Fuel Off-Road",
    brandSlug: "fuel-offroad",
    category: "Automotive",
    image: {
      src: "/gear/fuel-gripper-mt.png",
      alt: "Fuel Gripper M/T 33-inch mud-terrain tyre",
      width: 1000,
      height: 1000,
    },
    summary:
      "Aggressive 33-inch mud-terrains with a protruding sidewall, high-void tread and a stiff, puncture-resistant carcass — traction in the thick stuff, quiet enough for the road between.",
    useCase: "Mud, rock and remote touring on the loaded camper.",
    reasonSelected:
      "A true M/T with the load range and sidewall strength for a fully-laden camper, in a 17\" fitment to clear the big brakes.",
    sponsorshipStatus: "supplied",
    purchaseUrl: "https://www.fueloffroad.com/tires",
    specifications: [
      { label: "Size", value: "33×12.50R17LT" },
      { label: "Load Range", value: "E (10PR)" },
      { label: "Speed / Load", value: "120Q" },
      { label: "Max Load", value: "3085", unit: "lb" },
      { label: "Overall Dia.", value: "33", unit: "in" },
      { label: "Max Pressure", value: "65", unit: "PSI" },
    ],
    buildSystemSlugs: ["80-series-chassis"],
    region: "AU",
    featured: true,
  },
  {
    id: "pr-kc-flexera4",
    name: "KC FLEX ERA 4",
    slug: "kc-flex-era-4",
    brandName: "KC HiLiTES",
    brandSlug: "kc-hilites",
    category: "Automotive",
    image: {
      src: "/gear/kc-flex-era-4.jpg",
      alt: "KC HiLiTES FLEX ERA 4 LED light",
      width: 1000,
      height: 1000,
    },
    summary:
      "The big-hitter of the FLEX ERA family — long-range LED output for the front bar plus a pair mounted as ditch lights.",
    useCase: "Front bar driving lights and A-pillar ditch lights.",
    reasonSelected: "Swappable optics and serious reach for remote night driving.",
    sponsorshipStatus: "supplied",
    purchaseUrl: "https://kchilites.com.au/",
    specifications: [
      { label: "Series", value: "FLEX ERA 4" },
      { label: "Kit", value: "2-Light Master Kit" },
      { label: "Mounting", value: "Front bar + ditch" },
      { label: "Optics", value: "Interchangeable" },
    ],
    buildSystemSlugs: ["electrical-control-systems"],
    region: "AU",
    featured: true,
  },
  {
    id: "pr-kc-flexera1",
    name: "KC FLEX ERA 1",
    slug: "kc-flex-era-1",
    brandName: "KC HiLiTES",
    brandSlug: "kc-hilites",
    category: "Automotive",
    image: {
      src: "/gear/kc-flex-era-1.jpg",
      alt: "KC HiLiTES FLEX ERA 1 LED light",
      width: 1000,
      height: 1000,
    },
    summary:
      "The compact single-lens FLEX ERA — tucked in as rear and side scene lighting around the habitat for setting up camp after dark.",
    useCase: "Rear and side work/scene lighting on the habitat.",
    reasonSelected: "Small footprint, flood optics and the same rugged FLEX ERA build.",
    sponsorshipStatus: "supplied",
    purchaseUrl: "https://kchilites.com.au/",
    specifications: [
      { label: "Series", value: "FLEX ERA 1" },
      { label: "Kit", value: "2-Light Master Kit" },
      { label: "Mounting", value: "Habitat rear + sides" },
      { label: "Beam", value: "Scene / flood" },
    ],
    buildSystemSlugs: ["electrical-control-systems"],
    region: "AU",
    featured: true,
  },
  {
    id: "pr-battery",
    name: "300Ah Lithium Battery Bank",
    slug: "lithium-battery-bank",
    category: "Electronics",
    summary: "House power for lighting, fridge, water and the control system.",
    useCase: "Off-grid habitat power.",
    reasonSelected: "Deep cycling, weight and safety for a permanent install.",
    sponsorshipStatus: "personally-purchased",
    buildSystemSlugs: ["electrical-control-systems"],
    region: "AU",
    featured: true,
  },
  {
    id: "pr-pi",
    name: "Raspberry Pi 5",
    slug: "raspberry-pi-5",
    category: "Electronics",
    summary: "The UI brain running the Tesla-style digital dashboard.",
    useCase: "Touchscreen dashboard, maps, media, local server.",
    reasonSelected: "Flexible, well-documented, and easy to integrate cleanly.",
    sponsorshipStatus: "personally-purchased",
    buildSystemSlugs: ["electrical-control-systems"],
    region: "AU",
    featured: true,
  },
  {
    id: "pr-esp32",
    name: "ESP32-S3 Controllers",
    slug: "esp32-s3-controllers",
    category: "Electronics",
    summary: "The reliable nervous system switching loads and reading sensors.",
    useCase: "Cab, habitat and security controllers.",
    reasonSelected: "Rugged, cheap, and independently reliable of the main computer.",
    sponsorshipStatus: "personally-purchased",
    buildSystemSlugs: ["electrical-control-systems"],
    region: "AU",
  },
  {
    id: "pr-welder-tig",
    name: "Unimig Razor TIG 200 AC/DC",
    slug: "unimig-razor-tig-200",
    brandName: "Unimig",
    category: "Fabrication",
    image: {
      src: "/gear/unimig-razor-tig-200.png",
      alt: "Unimig Razor TIG 200 AC/DC welder with torch and regulator",
      width: 1000,
      height: 1000,
    },
    summary:
      "AC/DC TIG for the precision work — aluminium fabrication, thin steel and clean, controlled fusion welds.",
    useCase: "Aluminium and fine steel TIG work, brackets and detail fabrication.",
    reasonSelected: "AC/DC output and HF start for proper aluminium and thin-gauge control.",
    sponsorshipStatus: "personally-purchased",
    purchaseUrl: "https://unimig.com.au/product/razor-tig-200-ac-dc-welder/",
    specifications: [
      { label: "Process", value: "TIG AC/DC + MMA" },
      { label: "Max Output", value: "200", unit: "A" },
      { label: "Ignition", value: "HF Start" },
      { label: "Input", value: "240V Single Phase" },
    ],
    buildSystemSlugs: ["80-series-chassis", "wheelbase-extension"],
    region: "AU",
  },
  {
    id: "pr-welder-mig",
    name: "Unimig Envy Multi 195",
    slug: "unimig-envy-multi-195",
    brandName: "Unimig",
    category: "Fabrication",
    image: {
      src: "/gear/unimig-envy-195.png",
      alt: "Unimig Envy Multi 195 multi-process welder",
      width: 1000,
      height: 1000,
    },
    summary:
      "The multi-process workhorse — MIG for the heavy chassis and barwork, with TIG and stick on tap when the job changes.",
    useCase: "Chassis extension, engine plates and barwork.",
    reasonSelected: "One machine covering MIG, TIG and stick for thick frame steel through to panels.",
    sponsorshipStatus: "personally-purchased",
    purchaseUrl: "https://unimig.com.au/product/envy-multi-195-welder/",
    specifications: [
      { label: "Process", value: "MIG / TIG / MMA" },
      { label: "Max Output", value: "195", unit: "A" },
      { label: "Wire Feed", value: "Gas / Gasless" },
      { label: "Input", value: "240V Single Phase" },
    ],
    buildSystemSlugs: ["80-series-chassis", "wheelbase-extension"],
    region: "AU",
  },
  {
    id: "pr-cad",
    name: "Fusion 360",
    slug: "fusion-360",
    category: "Software",
    summary: "CAD for engine plates, brackets and 3D-printed parts.",
    useCase: "Design and fabrication drawings.",
    sponsorshipStatus: "personally-purchased",
    region: "Global",
  },
  {
    id: "pr-printer",
    name: "Bambu Lab P1S",
    slug: "bambu-lab-p1s",
    brandName: "Bambu Lab",
    category: "3D Printing",
    image: {
      src: "/gear/bambu-p1s.jpg",
      alt: "Bambu Lab P1S enclosed CoreXY 3D printer",
      width: 1000,
      height: 1000,
    },
    summary:
      "An enclosed CoreXY that prints jigs, prototypes and the screen shroud fast and repeatably — hot enough for engineering-grade filaments.",
    useCase: "Prototyping, fixtures and printed parts for the build.",
    reasonSelected: "Fast, enclosed and reliable — quality parts with almost no fuss.",
    sponsorshipStatus: "personally-purchased",
    purchaseUrl: "https://au.store.bambulab.com/products/p1s",
    specifications: [
      { label: "Build Volume", value: "256³", unit: "mm" },
      { label: "Nozzle", value: "0.4mm Steel" },
      { label: "Max Speed", value: "500", unit: "mm/s" },
      { label: "Chamber", value: "Enclosed CoreXY" },
    ],
    region: "AU",
  },
  {
    id: "pr-filament-proto",
    name: "Overture Rapid PETG",
    slug: "overture-rapid-petg",
    brandName: "Overture",
    category: "3D Printing",
    image: {
      src: "/gear/overture-petg.jpg",
      alt: "Overture Rapid PETG filament spool, 1.75mm black",
      width: 1000,
      height: 1000,
    },
    summary:
      "High-speed PETG for prototyping — tough, forgiving and cheap enough to iterate fast before committing to a final part.",
    useCase: "Prototype parts, jigs and test fits.",
    reasonSelected: "High-speed formulation and tight tolerances at a prototyping price.",
    sponsorshipStatus: "personally-purchased",
    purchaseUrl: "https://www.amazon.com.au/dp/B08N41KP81",
    specifications: [
      { label: "Material", value: "PETG (High Speed)" },
      { label: "Diameter", value: "1.75", unit: "mm" },
      { label: "Spool", value: "1", unit: "kg" },
      { label: "Tolerance", value: "±0.02", unit: "mm" },
    ],
    region: "AU",
  },
  {
    id: "pr-filament-final",
    name: "Elegoo PAHT-CF",
    slug: "elegoo-paht-cf",
    brandName: "Elegoo",
    category: "3D Printing",
    image: {
      src: "/gear/elegoo-paht.jpg",
      alt: "Elegoo PAHT-CF carbon-fibre nylon filament spool, 1.75mm black",
      width: 1000,
      height: 1000,
    },
    summary:
      "Carbon-fibre reinforced high-temp nylon for final parts — high strength, rigidity and heat resistance for brackets that live in the engine bay and cab.",
    useCase: "Final, load-bearing and heat-exposed printed parts.",
    reasonSelected: "Strength, stiffness and temperature resistance a step beyond standard filaments.",
    sponsorshipStatus: "personally-purchased",
    purchaseUrl: "https://www.amazon.com.au/dp/B0F37YW223",
    specifications: [
      { label: "Material", value: "PAHT-CF (Nylon)" },
      { label: "Diameter", value: "1.75", unit: "mm" },
      { label: "Spool", value: "1", unit: "kg" },
      { label: "Traits", value: "High Temp / Rigid" },
    ],
    region: "AU",
  },
];
